name: build website

# Trigger the workflow when the validation action finished
on:
  workflow_run:
    workflows: ["poseidon validate (trident)"]
    types:
      - completed

jobs:
  buildWebsite:
  
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # only run if the validation was successful
    name: build repo website
    runs-on: ubuntu-latest

    steps:

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        # Use the public version of RStudio package manager to serve binaries for Linux and Windows
        use-public-rspm: true
      
    - name: Install Pandoc
      uses: r-lib/actions/setup-pandoc@master
      
    - name: Install R depedencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 1
        working-directory: ./website_generator
        
    # - name: Build website
    #   run: 
      

    # - name: Deploy haddock documentation
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ${{ steps.haddockpath.outputs.DOCPATH }}
