name: poseidon validate (trident)

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  validate:
    name: poseidon-hs validation
    runs-on: ubuntu-latest
    steps:
        
    - name: Install trident
      run: |
        wget https://github.com/poseidon-framework/poseidon-hs/releases/latest/download/trident-Linux
        chmod +x trident-Linux
        
    - name: Clone data repo
      uses: actions/checkout@v2
      with:
        path: data

    - name: Validation
      run: |
        ./trident-Linux validate -d data --ignoreGeno
        
  buildWebsite:
    needs: validate
    name: build repo website
    runs-on: ubuntu-latest
    steps:

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      
    - name: Install Pandoc
      uses: r-lib/actions/setup-pandoc@master
      
    - name: Install R depedencies
      run: |
        install.packages(c("dplyr","DT","knitr","leaflet","magrittr","purrr","rmarkdown","yaml","remotes"))
        remotes::install_github('poseidon-framework/poseidonR')
      shell: Rscript {0}
